# This is for local development
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rrmondal12
      POSTGRES_DB: password-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - "redis_data:/var/lib/redis/data"

  backend:
    image: password_manager
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: password_manager_app
    environment:
      APP_ENVIRONMENT: "docker"
    depends_on:
      - postgres
      - redis
    ports:
      - "7000:7000"

  
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local