apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
    spec:
      containers:
        - name: password-manager
          image: imrahul7299/password-manager:latest
          env:
            - name: APP_ENVIRONMENT
              value: "docker"

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

          ports:
            - containerPort: 7000
          command: ["./password_manager_webapp"]
---
apiVersion: v1
kind: Service
metadata:
  name: password-manager
spec:
  selector:
    app: password-manager
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: NodePort
