application:
  name: "Password-Manager"
  port: 6966
  host: "localhost"
  jwt_key: "UnJtb25kYWwxMkAK"
  jwt_exp: 3600
  log_level: "INFO"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "Rrmondal12"
  name: "PasswordManager"