frontend:
  url : "localhost:3000"
application:
  name: "Password-Manager"
  port: 6428
  host: "localhost"
  jwt_key: "UnJtb25kYWwxMkAK"
  jwt_exp: 3600
  log_level: "INFO"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "Rrmondal12"
  name: "password-manager"
  