frontend:
  url : "http://localhost:3000"
application:
  name: "Password-Manager"
  port: 7000
  host: "localhost"
  jwt_key: "UnJtb25kYWwxMkAK"
  jwt_exp: 900
  log_level: "INFO"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "Rrmondal12"
  name: "password-manager"
  